name: Danger Swift

on: [pull_request]

jobs:
  danger:
    name: Danger
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
            ruby-version: '2.x'
            architecture: 'x64'
      - name: cache bundle
        uses: actions/cache@v1
        with:
          key: bundle-${{ hashFiles('**/Gemfile.lock') }}
      - name: bundle install
        run: |
          gem install bundler
          bundle install
      - name: Run Danger
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          bundle exec danger

